apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      host: clickhouse
      port: 9000
      database: proofgate
      username: default
      secure: false
    editable: false
