// Package server provides enterprise-grade capabilities, configuration, and structural components for the server subsystem.
package server

import (
	"context"
	"errors"
	"log/slog"
	"sync"
	"sync/atomic"
	"time"

	"github.com/proofgate/proofgate/internal/api"
	"github.com/proofgate/proofgate/internal/health"
	"github.com/proofgate/proofgate/internal/pipeline"
	"github.com/proofgate/proofgate/internal/provider"
	"github.com/proofgate/proofgate/internal/router"
)

var (
	// unpricedLogMu protects the unpricedLogged rate-limiting map.
	unpricedLogMu sync.Mutex
	// unpricedLogged tracks the last time an unpriced target was logged to prevent log spam.
	unpricedLogged = make(map[string]time.Time)
)

// logUnpricedTarget emits a warning log when a target model has no configured pricing.
// It rate-limits the warning to at most once per hour per target to avoid flooding the log sink
// during high-traffic unpriced traffic bursts.
func logUnpricedTarget(target string) {
	unpricedLogMu.Lock()
	defer unpricedLogMu.Unlock()
	last, ok := unpricedLogged[target]
	now := time.Now()
	if !ok || now.Sub(last) > time.Hour {
		unpricedLogged[target] = now
		slog.Warn("call to unpriced target", "target", target)
	}
}

// outcome translates underlying raw errors into health tracker semantics.
// This is critical for the circuit breakers to differentiate between:
// - health.Failed: Provider is actually failing (e.g., 500, 502, 503).
// - health.Unknown: Client fault (400, 422, client disconnect), so don't punish the provider's health score.
// - health.OK: Successful generation.
func outcome(err error) health.Outcome {
	var pe *provider.Error
	switch {
	case err == nil:
		return health.OK
	case errors.As(err, &pe):
		// 400 Bad Request, 404 Not Found, 413 Payload Too Large, 422 Unprocessable Entity
		// These indicate client-side payload issues, not provider degradation.
		if pe.Status == 400 || pe.Status == 404 || pe.Status == 413 || pe.Status == 422 {
			return health.Unknown
		}
		return health.Failed
	case errors.Is(err, context.Canceled):
		// The downstream client aborted the connection before completion.
		return health.Unknown
	default:
		return health.Failed
	}
}

// observe propagates a single generation outcome to the background gossip health tracker.
// This updates the EWMA latency arrays and increments failure counters for smart routing.
func (h *Handlers) observe(s health.Sample) {
	if h.Health != nil {
		h.Health.Observe(s)
	}
}

// planFor generates the sequence of targets to attempt for a given request.
// If the call already possesses an explicitly forced Target, it prepends that target
// and deduplicates it from the standard fallback sequence generated by the routing engine.
func planFor(rt *Runtime, c *pipeline.Call) []router.Target {
	if c.Target.Provider != "" && c.Target.Model != "" {
		plan := []router.Target{c.Target}
		for _, t := range rt.Router.Plan(c.Route, c.Request) {
			if t != c.Target {
				plan = append(plan, t)
			}
		}
		// Finalizes priority queueing logic for the modified plan
		return rt.Router.Order(plan)
	}
	return rt.Router.Plan(c.Route, c.Request)
}

// price calculates the token usage and fiat cost of a completed call.
// It extracts exact usage if the provider supplied it, otherwise it relies on
// heuristic token estimation (EstimatePromptTokens). If the tenant has a strictly
// enforced fiat budget but the target lacks pricing data, this intentionally errors the request
// to prevent "infinite free usage" exploits.
func price(rt *Runtime, c *pipeline.Call, completionText string) {
	if c.Response != nil && c.Response.Usage != nil {
		c.Usage = *c.Response.Usage
	} else {
		prompt := c.Request.EstimatePromptTokens()
		comp := api.EstimateTokens(completionText)
		c.Usage = api.Usage{PromptTokens: prompt, CompletionTokens: comp, TotalTokens: prompt + comp}
		c.Values["usage.estimated"] = true
	}

	if cost, ok := rt.Pricing.CostMicros(c.Target.String(), c.Usage); ok {
		c.CostMicros = cost
	} else {
		c.Values["cost.unpriced"] = true
		logUnpricedTarget(c.Target.String())
		// If strict budgeting is required but the route has no cost configured, abort the transaction.
		if c.Principal.Tenant.BudgetMicros() > 0 && rt.Config != nil && rt.Config.Budget.IsRequirePricing() && c.Err == nil {
			c.Err = &api.Error{
				Status:  500,
				Message: "target pricing unconfigured",
				Type:    "api_error",
				Code:    "unpriced_target",
			}
		}
	}
}

// execChat governs the upstream execution phase for standard (non-streaming) completions.
// It orchestrates:
// 1. Fetching the ordered target fallback plan.
// 2. Establishing per-request timeouts.
// 3. Spawning the synchronous network call to the LLM adapter (e.g. OpenAI/Anthropic SDKs).
// 4. Executing Tail-Latency Hedging (if configured on the route and concurrent tokens permit).
// 5. Feeding resulting RTT latencies back into the smart routing health monitor.
// 6. Computing usage/fiat prices based on the resulting tokens.
func (h *Handlers) execChat(ctx context.Context, rt *Runtime, c *pipeline.Call) error {
	deadline := c.Route.Deadline
	if deadline <= 0 {
		deadline = 90 * time.Second
	}
	plan := planFor(rt, c)

	// fn defines the core unit of work: pinging a single provider target.
	fn := func(ctx context.Context, t router.Target) (*api.ChatResponse, error) {
		if c.Route.Timeout > 0 {
			var cancel context.CancelFunc
			ctx, cancel = context.WithTimeout(ctx, c.Route.Timeout)
			defer cancel()
		}
		p, ok := rt.Registry.Get(t.Provider)
		if !ok {
			return nil, api.NoHealthyTarget()
		}
		start := time.Now()
		resp, err := p.Chat(ctx, t.Model, c.Request)
		atomic.AddInt64((*int64)(&c.UpstreamTime), int64(time.Since(start)))

		s := health.Sample{Target: t, Outcome: outcome(err), Gen: time.Since(start)}
		if err == nil && resp != nil && resp.Usage != nil {
			s.Tokens = resp.Usage.CompletionTokens
		}
		h.observe(s)

		if err != nil {
			return nil, err
		}
		return resp, nil
	}

	var (
		resp   *api.ChatResponse
		res    router.Result
		hedged bool
		err    error
	)

	// Branch: Hedged Execution
	// If the route permits tail-latency hedging and we have >= 2 fallback targets available.
	if c.Route.Hedge.Enabled && len(plan) >= 2 {
		b := h.hedgeBudget(c.Route)
		b.Request() // Ask the concurrency controller for a hedging token

		defDelay := 150 * time.Millisecond
		if c.Route.Hedge.Delay > 0 {
			defDelay = c.Route.Hedge.Delay
		}
		delay := defDelay

		// If Smart Routing is active, dynamically calculate the hedge delay using P90/P99 histograms.
		if h.Health != nil {
			delay = h.Health.HedgeDelay(plan[0], defDelay)
		}

		resp, res, hedged, err = router.ExecuteHedged[*api.ChatResponse](
			ctx, plan, c.Route.Retry, h.Breakers, deadline, delay,
			func() bool {
				allowed := b.Allow()
				if allowed && h.Metrics != nil {
					h.Metrics.ObserveHedge(c.Route.Name, "launched")
				}
				return allowed
			},
			fn,
			nil, // Cancel hooks omitted for non-streaming
		)

		if hedged {
			c.Header.Set("X-ProofGate-Hedged", "true")
			if h.Metrics != nil {
				if err == nil {
					// Wasted tokens calculation: The loser's prompt tokens cost money but we discard their answer.
					wastedTokens := c.Request.EstimatePromptTokens()
					if res.Target == plan[0] { // The primary target won (hedge was wasted)
						h.Metrics.ObserveHedge(c.Route.Name, "lost")
						h.Metrics.ObserveHedgeWaste(c.Route.Name, plan[1].String(), wastedTokens)
						if cost, ok := rt.Pricing.EstimateMaxMicros([]string{plan[1].String()}, wastedTokens, 0); ok {
							atomic.AddInt64(&c.HedgeCostMicros, cost)
						}
					} else { // The hedge target won (primary was wasted)
						h.Metrics.ObserveHedge(c.Route.Name, "won")
						h.Metrics.ObserveHedgeWaste(c.Route.Name, plan[0].String(), wastedTokens)
						if cost, ok := rt.Pricing.EstimateMaxMicros([]string{plan[0].String()}, wastedTokens, 0); ok {
							atomic.AddInt64(&c.HedgeCostMicros, cost)
						}
					}
				}
			}
		}
	} else {
		// Branch: Standard sequential fallback execution without concurrency
		res, err = router.Execute(ctx, plan, c.Route.Retry, h.Breakers, deadline, func(ctx context.Context, t router.Target) error {
			r, e := fn(ctx, t)
			if e == nil {
				resp = r
			}
			return e
		})
	}

	c.Target, c.Attempts = res.Target, res.Attempts
	if err != nil {
		return err
	}
	c.Response = resp
	text := ""
	if len(c.Response.Choices) > 0 {
		text = c.Response.Choices[0].Message.Content.PlainText()
	}

	// Finalize post-generation telemetry and accounting
	price(rt, c, text)
	return nil
}
