apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proofgate.fullname" . }}
  labels:
    {{- include "proofgate.labels" . | nindent 4 }}
data:
  proofgate.yaml: |
{{ .Values.config | indent 4 }}
