FROM golang:latest AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags "-s -w" -o /out/mockllm ./cmd/mockllm

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/mockllm /usr/local/bin/mockllm
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/mockllm"]
